"use client";

import { useEffect, useRef } from "react";
import Laboratory from "./Laboratory";
import { useLanguage } from "../i18n/LanguageContext";

const exact = {
"EXPERIMENTO":"EXPERIMENT","ENTRAR AL SIMULADOR →":"ENTER SIMULATOR →","TODOS LOS EXPERIMENTOS":"ALL EXPERIMENTS","🔬 REGLA DEL LABORATORIO:":"🔬 LAB RULE:","toca, arrastra y experimenta. Aquí aprendes haciendo que el Universo cambie delante de ti.":"tap, drag, and experiment. Here you learn by making the Universe change right in front of you.","MUNDO EXTREMO":"EXTREME WORLD","NUEVO":"NEW",
"SUPERGRAVEDAD":"SUPERGRAVITY","Salta en la Luna, Marte o Júpiter.":"Jump on the Moon, Mars, or Jupiter.","Elige un mundo y pulsa SALTAR. Usamos siempre el mismo impulso para que veas de verdad cómo cambia el movimiento.":"Choose a world and press JUMP. We always use the same push so you can really see how gravity changes motion.","SALTAR":"JUMP","GRAVEDAD":"GRAVITY","TU PESO":"YOUR WEIGHT","TIEMPO DE SALTO":"JUMP TIME","ALTURA VISUAL":"VISUAL HEIGHT",
"DOMINA UNA ÓRBITA":"MASTER AN ORBIT","Mueve un planeta y cambia su año.":"Move a planet and change the length of its year.","Arrastra el planeta. Acercarlo al Sol lo hace viajar más rápido; alejarlo alarga su viaje.":"Move the planet. Bringing it closer to the Sun makes it travel faster; moving it farther away makes its year longer.","🔥 Cerca":"🔥 Close","❄️ Lejos":"❄️ Far","ÓRBITAS VISUALIZADAS A ESCALA EDUCATIVA":"ORBITS SHOWN AT AN EDUCATIONAL SCALE","VELOCIDAD":"SPEED","DURACIÓN DEL AÑO":"YEAR LENGTH","TENDENCIA TÉRMICA":"TEMPERATURE TREND","MUY CALIENTE":"VERY HOT","MUY FRÍA":"VERY COLD","TEMPLADA":"MILD",
"FABRICA UN DÍA":"MAKE A DAY","Acelera la rotación de un mundo.":"Speed up a world's rotation.","Acelera o frena el giro del planeta. Sigue la ciudad luminosa mientras entra y sale de la noche.":"Speed up or slow down the planet's rotation. Follow the glowing city as it moves into daylight and night.","⚡ Giro rápido":"⚡ Fast rotation","🐢 Giro lento":"🐢 Slow rotation","NOCHE":"NIGHT","AMANECER":"DAWN","DÍA":"DAY","MEDIODÍA":"MIDDAY","▶ REANUDAR PLANETA":"▶ RESUME PLANET","⏸ CONGELAR PLANETA":"⏸ FREEZE PLANET","ROTACIÓN":"ROTATION","COMPARADA CON TIERRA":"COMPARED WITH EARTH","MÁS RÁPIDA":"FASTER","MÁS LENTA":"SLOWER","IGUAL":"SAME","EN TU CIUDAD":"IN YOUR CITY","El Sol no “se apaga” por la noche. Es el planeta el que gira y lleva tu ciudad hacia la cara que queda de espaldas a su estrella.":"The Sun does not 'switch off' at night. The planet rotates and carries your city onto the side facing away from its star.",
"AGUJERO NEGRO":"BLACK HOLE","¿Qué ocurre si te acercas demasiado?":"What happens if you get too close?","ACÉRCATE A UN AGUJERO NEGRO":"APPROACH A BLACK HOLE","Pilota una nave hacia el horizonte de sucesos. La escena se deforma cada vez más a medida que entras en una región de gravedad extrema.":"Pilot a spacecraft toward the event horizon. The scene becomes more distorted as you enter a region of extreme gravity.","☠ HORIZONTE":"☠ EVENT HORIZON","🚀 LEJOS":"🚀 FAR","ESPACIO NORMAL":"NORMAL SPACE","GRAVEDAD INTENSA":"INTENSE GRAVITY","FUERZAS DE MAREA":"TIDAL FORCES","JUNTO AL HORIZONTE":"NEAR THE HORIZON","HORIZONTE CRUZADO":"HORIZON CROSSED","⚠ HORIZONTE DE SUCESOS: NO HAY REGRESO":"⚠ EVENT HORIZON: NO WAY BACK","⚠ FUERZAS DE MAREA EXTREMAS":"⚠ EXTREME TIDAL FORCES","BAJAS":"LOW","CRECIENDO":"RISING","EXTREMAS":"EXTREME","CRÍTICAS":"CRITICAL","DILATACIÓN TEMPORAL":"TIME DILATION","ESTADO":"STATUS","Representación educativa: exageramos visualmente la deformación para que el fenómeno sea comprensible. La forma exacta depende de la masa y rotación del agujero negro y de la trayectoria del observador.":"Educational representation: the distortion is visually exaggerated to make the phenomenon easier to understand. Its exact appearance depends on the black hole's mass and rotation and on the observer's path.",
"IMPACTO DE ASTEROIDE":"ASTEROID IMPACT","Cambia el tamaño y la velocidad del impacto.":"Change the asteroid's size and impact speed.","Lanza el asteroide y observa el terreno después del choque. El cráter final y la onda expansiva cambian con el tamaño y la velocidad.":"Launch the asteroid and watch the ground after impact. The final crater and shock wave change with its size and speed.","☄️ LANZAR ASTEROIDE":"☄️ LAUNCH ASTEROID","CRÁTER ESTIMADO":"ESTIMATED CRATER","ONDA EXPANSIVA":"SHOCK WAVE","ENERGÍA RELATIVA":"RELATIVE ENERGY","RESULTADO":"RESULT","diámetro visual relativo":"relative visual diameter","radio educativo":"educational radius","respecto al ajuste inicial":"compared with the starting setting","clasificación educativa":"educational classification","IMPACTO PEQUEÑO":"SMALL IMPACT","IMPACTO LOCAL":"LOCAL IMPACT","IMPACTO REGIONAL":"REGIONAL IMPACT","IMPACTO CATASTRÓFICO":"CATASTROPHIC IMPACT","Modelo educativo simplificado: el tamaño real del cráter y la onda expansiva dependen también de densidad, ángulo de entrada, terreno, atmósfera y composición del asteroide.":"Simplified educational model: the real crater size and shock wave also depend on density, entry angle, terrain, atmosphere, and the asteroid's composition.",
"HAS DESCUBIERTO":"YOU DISCOVERED","NOTA CIENTÍFICA":"SCIENCE NOTE"
};
const dynamic=[
[/^EXPERIMENTO (.+)$/,(_,x)=>`EXPERIMENT ${x.replace("MUNDO EXTREMO","EXTREME WORLD")}`],[/^SALTO EN (.+)$/,(_,x)=>`JUMP ON ${world(x)}`],[/^TU MASA · (.+)$/,(_,x)=>`YOUR MASS · ${x}`],[/^DISTANCIA · (.+) UA$/,(_,x)=>`DISTANCE · ${x} AU`],[/^UN DÍA DURA · (.+) HORAS$/,(_,x)=>`ONE DAY LASTS · ${x} HOURS`],[/^DISTANCIA DE SEGURIDAD · (.+)$/,(_,x)=>`SAFE DISTANCE · ${x}`],[/^DIÁMETRO · (.+)$/,(_,x)=>`DIAMETER · ${x}`],[/^VELOCIDAD · (.+)$/,(_,x)=>`SPEED · ${x}`]
];
const worldMap={"Luna":"Moon","Marte":"Mars","Tierra":"Earth","Neptuno":"Neptune","Júpiter":"Jupiter"};
function world(s){return worldMap[s]||s}
function sentences(s){
 if(s==="Estás en la Tierra: esta es nuestra referencia. El salto que ves representa un salto terrestre normal.")return "You are on Earth: this is our reference. The jump shown represents a normal Earth jump.";
 let m=s.match(/^¡Casi flotas! En (.+) puedes permanecer mucho más tiempo en el aire porque la gravedad es mucho menor que en la Tierra\.$/);if(m)return `You almost float! On ${world(m[1])}, you can stay in the air much longer because gravity is much weaker than on Earth.`;
 m=s.match(/^En (.+) la gravedad te pega al suelo\. El mismo impulso apenas consigue levantarte\.$/);if(m)return `On ${world(m[1])}, gravity pulls you hard toward the ground. The same push barely lifts you up.`;
 m=s.match(/^En (.+) la gravedad es distinta a la terrestre y eso cambia la altura y duración del mismo salto\.$/);if(m)return `Gravity on ${world(m[1])} is different from Earth's, changing both the height and duration of the same jump.`;
 const map={
 "Has llevado el planeta muy cerca: recibe mucha más energía del Sol y se mueve a gran velocidad.":"You moved the planet very close to the Sun: it receives much more solar energy and travels very fast.","Aquí el Sol calienta mucho menos y el planeta tarda bastante más en completar su año.":"Here the Sun provides much less heat, and the planet takes much longer to complete its year.","Estás cerca de la zona de la órbita terrestre. Sigue moviendo el planeta y compara.":"You are close to Earth's orbital region. Keep moving the planet and compare what happens.",
 "A gran distancia, la nave puede mantenerse lejos de la zona más peligrosa.":"Far away, the spacecraft can stay clear of the most dangerous region.","La trayectoria de la luz empieza a curvarse de forma extrema en la visualización y la nave cae hacia una región cada vez más intensa.":"The path of light begins to bend dramatically in the visualization as the spacecraft falls toward an increasingly intense region.","Las fuerzas de marea crecen rápidamente: la gravedad tira con distinta intensidad de unas partes de la nave y de otras.":"Tidal forces grow quickly: gravity pulls different parts of the spacecraft with different strengths.","Estás peligrosamente cerca del horizonte de sucesos. Para un observador lejano, los efectos relativistas se vuelven enormes.":"You are dangerously close to the event horizon. For a distant observer, relativistic effects become enormous.","Has cruzado el horizonte de sucesos en la simulación. Nada que esté dentro puede enviar una señal de vuelta al exterior.":"You crossed the event horizon in the simulation. Nothing inside it can send a signal back out.",
 "El cráter es pequeño y la onda expansiva alcanza una zona limitada. Aumenta el diámetro o la velocidad y vuelve a lanzar.":"The crater is small and the shock wave reaches a limited area. Increase the diameter or speed and launch again.","El impacto ya excava un cráter mucho mayor y la onda expansiva cubre una zona claramente más amplia.":"The impact now digs a much larger crater and the shock wave covers a clearly wider area.","La onda de choque recorre una gran superficie y el cráter crece de forma muy visible. La energía aumenta con enorme rapidez.":"The shock wave travels across a large area and the crater grows dramatically. The energy rises extremely quickly.","Has creado un impacto extremo: el cráter domina la zona de choque y la onda expansiva se extiende muy lejos del punto de impacto.":"You created an extreme impact: the crater dominates the impact zone and the shock wave spreads far from the impact point."
 };return map[s];
}
function tr(value){const lead=value.match(/^\s*/)?.[0]||"",tail=value.match(/\s*$/)?.[0]||"",s=value.trim().replace(/\s+/g," ");if(!s)return value;let out=exact[s]||sentences(s);if(!out){for(const[r,f]of dynamic){const m=s.match(r);if(m){out=f(...m);break;}}}if(!out&&worldMap[s])out=worldMap[s];if(!out)return value;return lead+out+tail;}
export default function LocalizedLaboratory(){const {language}=useLanguage();const rootRef=useRef(null);const en=language==="en";useEffect(()=>{const root=rootRef.current;if(!root)return;let busy=false;const one=(node,refresh=false)=>{if(node.nodeType!==Node.TEXT_NODE)return;const current=node.nodeValue||"";if(refresh&&current!==node.__labLocalized)node.__labOriginal=current;const original=node.__labOriginal??current;node.__labOriginal=original;const next=en?tr(original):original;node.__labLocalized=next;if(current!==next)node.nodeValue=next;};const tree=target=>{if(target.nodeType===Node.TEXT_NODE){one(target);return;}const w=document.createTreeWalker(target,NodeFilter.SHOW_TEXT);let n=w.nextNode();while(n){one(n);n=w.nextNode();}};tree(root);const obs=new MutationObserver(ms=>{if(busy)return;busy=true;try{ms.forEach(m=>m.type==="characterData"?one(m.target,true):m.addedNodes.forEach(tree));}finally{busy=false;}});obs.observe(root,{childList:true,subtree:true,characterData:true});return()=>obs.disconnect();},[en]);return <div ref={rootRef} style={{display:"contents"}}><Laboratory/></div>}
